version: '3'
services:
  app:
    build: C:\Users\trosh\Desktop\pitoncheg\Python_work\dockertest\app\csvapp\csv project\csvproject
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000